[tool.black]
line-length = 120
complexity = 10
include = '\.py?$'
force-exclude = '''
(
  /(
    | \.git
    | \.cache
    | \.pytest_cache
    | \.venv
    | migrations
    | static
  )/
  | Dockerfile
  | Makefile
  | pyproject.toml
  | README.md
  | requirements.txt
  | tailwind.config.js
)
'''